<?php
/**
 * Printable Diagnostic Report Template.
 *
 * @var array $snap Dashboard snapshot for the last 30 days.
 * @package SmartPluginMonitor
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php esc_html_e( 'Plugin Diagnostic Report', 'smart-performance-monitor' ); ?></title>
    <?php
    wp_enqueue_style( 'spmbyma-print', SPMBYMA_PLUGIN_URL . 'assets/css/print-report.css', [], '1.2.0' );
    wp_print_styles( 'spmbyma-print' );
    ?>
</head>
<body onload="window.print()">

    <div class="no-print" style="background: #3b82f6; color: #fff; padding: 10px 20px; margin: -40px -40px 40px -40px; display: flex; justify-content: space-between; align-items: center;">
        <span><?php esc_html_e( 'Report Preview — Use browser print dialog to save as PDF', 'smart-performance-monitor' ); ?></span>
        <button onclick="window.close()" style="background: rgba(255,255,255,0.2); border: 1px solid #fff; color: #fff; padding: 5px 15px; border-radius: 4px; cursor: pointer;">
            <?php esc_html_e( 'Close', 'smart-performance-monitor' ); ?>
        </button>
    </div>

    <header class="report-header">
        <div>
            <h1 class="report-title"><?php esc_html_e( 'Plugin Diagnostic Report', 'smart-performance-monitor' ); ?></h1>
            <p class="report-meta"><?php echo esc_html( get_bloginfo( 'name' ) ); ?> · <?php echo esc_html( get_site_url() ); ?></p>
        </div>
        <div class="report-meta">
            <?php printf( esc_html__( 'Generated: %s', 'smart-performance-monitor' ), esc_html( $snap['generated_at'] ) ); ?>
        </div>
    </header>

    <div class="summary-grid">
        <div class="summary-card">
            <div class="summary-label"><?php esc_html_e( 'Health Score', 'smart-performance-monitor' ); ?></div>
            <div class="summary-value"><?php echo esc_html( $snap['summary']['avg_score'] ); ?></div>
        </div>
        <div class="summary-card">
            <div class="summary-label"><?php esc_html_e( 'Plugins Tracked', 'smart-performance-monitor' ); ?></div>
            <div class="summary-value"><?php echo esc_html( $snap['summary']['total_plugins'] ); ?></div>
        </div>
        <div class="summary-card">
            <div class="summary-label"><?php esc_html_e( 'Total Errors', 'smart-performance-monitor' ); ?></div>
            <div class="summary-value"><?php echo esc_html( $snap['summary']['total_errors'] ); ?></div>
        </div>
        <div class="summary-card">
            <div class="summary-label"><?php esc_html_e( 'Analysis Window', 'smart-performance-monitor' ); ?></div>
            <div class="summary-value">30 Days</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th><?php esc_html_e( 'Plugin', 'smart-performance-monitor' ); ?></th>
                <th><?php esc_html_e( 'Avg Speed', 'smart-performance-monitor' ); ?></th>
                <th><?php esc_html_e( 'Errors', 'smart-performance-monitor' ); ?></th>
                <th><?php esc_html_e( 'Score', 'smart-performance-monitor' ); ?></th>
                <th><?php esc_html_e( 'Grade', 'smart-performance-monitor' ); ?></th>
                <th><?php esc_html_e( 'Trend', 'smart-performance-monitor' ); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ( $snap['plugins'] as $p ) : ?>
            <tr>
                <td><strong><?php echo esc_html( $p['plugin_name'] ); ?></strong></td>
                <td><?php echo esc_html( $p['avg_ms'] ); ?> ms</td>
                <td><?php echo esc_html( $p['error_count'] ); ?></td>
                <td><?php echo esc_html( $p['score'] ); ?></td>
                <td>
                    <span class="grade grade-<?php echo esc_attr( strtolower( $p['grade'] ) ); ?>">
                        <?php echo esc_html( $p['grade'] ); ?>
                    </span>
                </td>
                <td><?php echo esc_html( ucfirst( $p['trend'] ?? 'stable' ) ); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <footer style="margin-top: 60px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8; text-align: center;">
        <p><?php esc_html_e( 'Confidential Diagnostic Report · Generated by Smart Plugin Monitor', 'smart-performance-monitor' ); ?></p>
    </footer>

</body>
</html>
